wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1747925094.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 7
      - 23
      4: 3.11.11
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: valid_loss
      5: 1
      6:
      - 1
    - 1: val_epoch_acc
      5: 1
      6:
      - 1
    - 1: val_epoch_loss
      5: 1
      6:
      - 1
